trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: AzureCLI@1
  displayName: 'Install the CLI'
  inputs:
    azureSubscription: 'DIG Service Principal'
    scriptLocation: inlineScript
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@1
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: 'DIG Service Principal'
    scriptLocation: inlineScript
    inlineScript: 'az ml folder attach -w machine-learning-playground -g shared-research'

# - task: AzureCLI@1
#   displayName: 'Create compute for training'
#   inputs:
#     azureSubscription: 'DIG Service Principal'
#     scriptLocation: inlineScript
#     inlineScript: |
#         az ml computetarget create amlcompute -n cpu --vm-size STANDARD_D2_V2 --max-nodes 4
  
# - task: AzureCLI@1
#   displayName: 'Submit script run'
#   inputs:
#     azureSubscription: 'DIG Service Principal'
#     scriptLocation: inlineScript
#     inlineScript: 'az ml run submit-script -c sklearn -e test -d myenv.yml train.py'

# - task: AzureCLI@1
#   displayName: 'Register model'
#   inputs:
#     azureSubscription: 'DIG Service Principal'
#     scriptLocation: inlineScript
#     inlineScript: 'az ml model register -n registeredmodel -p sklearn_regression_model.pkl -t model.json'

- task: AzureCLI@1
  displayName: 'Deploy model'
  inputs:
    azureSubscription: 'DIG Service Principal'
    scriptLocation: inlineScript
    inlineScript: 'az ml model deploy -n demomodel -m registeredmodel:7 --ic inferenceconfig.json --dc deploymentconfig.json --debug --overwrite'

# - task: AzureCLI@1
#   displayName: 'Delete deployed service'
#   inputs:
#     azureSubscription: 'DIG Service Principal'
#     scriptLocation: inlineScript
#     inlineScript: 'az ml service delete -n acicicd'
